### ISSUE TITLE
Cant create repo : Compiling src/poolboy.erl failed

### ISSUE THREAD

**Issue by joshchernoff** [vigetlabs/jambells#44]
Forgive me since this is my first time using elixir.
When following the steps at creating the repo I hit a little wall. 

`~ mix ecto.create Repo                                                                                                                                          
==> poolboy (compile)
Compiling src/poolboy.erl failed:
src/poolboy.erl:17: type queue() undefined
ERROR: compile failed while processing /Users/*****/jambells/deps/poolboy: rebar_abort
`

I then try to mix deps.compile poolboy but get the same results. 

Thoughts?

**Comment by digitalcake** [comment]
After a deep look I think I maybe using too new of a version of elixir. 

`==> linguist
warning: the dependency :linguist requires Elixir "~> 0.15.1 or ~> 1.0.0-rc1" but you are running on v1.2.4
lib/linguist/compiler.ex:69: warning: you are piping into a function call without parentheses, which may be ambiguous. Please wrap the function you are piping into in parentheses. For example:

    foo 1 |> bar 2 |> baz 3

Should be written as:

    foo(1) |> bar(2) |> baz(3)
`
