### ISSUE TITLE
[Issue] JamBells Not Working

### ISSUE THREAD

**Issue by RachelBush** [vigetlabs/jambells#45]
When using an iPhone in a Google Chrome browser, I'm unable to get JamBells to work. I select 'Start a Choir,' Jingle Bells, and 'I'm Ready' and nothing happens. 

Others have experienced this as well.

**Comment by efatsi** [comment]
Got this fixed!

Unfortunately the deploy process on this app is so old that it doesn't work anymore, but the fix here was so small (changing `ws` to `wss` in a built javascript file, similar to the difference between `http` and `https`) that I just manually updated the file on the server.

That means though that if we wanted to make any updates to this at all, we'd probably need some CJones time to help troubleshoot the build/deploy process.
